- api/model.py
- requirements.txt
- swagger/api_spec.yaml
- transcription_API_server.py
Implement the ability to upload files to the API endpoints.
Will close #1
> [MRG] flask-uploads

- api/backend.py
- swagger/api_spec.yaml
Create endpoint to query the capabilities of the backend transcribing package.
> [MRG] Feature backend capabilities

- tests/conftest.py
> [MRG] Upload files to temporary directory

- api/utterance.py
> [MRG]Check for existing utterance before duplicating it

- swagger/api_spec.yaml
> [MRG] Fix missing response codes in API specification

- api/audio.py
- swagger/api_spec.yaml
> [MRG] Feature audio search endpoint

- api/transcription.py
- swagger/api_spec.yaml
> [MRG] Feature transcription search endpoint

- api/utterance.py
- swagger/api_spec.yaml
> [MRG] Feature utterance search endpoint

- api/audio.py
- api/transcription.py
> Refactor to use serialization schemas

- api/serialization.py
- api/utterance.py
> [MRG] Refactor utterance schema

- api/serialization.py
> [MRG] Exclude duplicated serialization result

- api/corpus.py
- api/db_models.py
- api/model.py
- api/serialization.py
- swagger/api_spec.yaml
- tests/test_model_endpoints.py
> [MRG] Feature model definition endpoint

- .gitignore
- API_testing/create_data.sh
- api/corpus.py
- api/db_models.py
- api/serialization.py
- api/utterance.py
- examples/requests_example.py
- swagger/api_spec.yaml
- swagger/flask_app.py
- tests/test_persephone_corpus_creation.py
- transcription_API_server.py
Create a Persephone Corpus object from the API.
Note this will be a blocking call as the job queue is not implemented yet.
> [MRG] Corpus creation

- persephone_api/api_endpoints/model.py
- persephone_api/api_spec.yaml
- persephone_api/db_models.py
- tests/conftest.py
- transcription_API_server.py
> [WIP] Create persphone.Model objects from API

- tests/conftest.py
- tests/test_corpus_endpoint.py
- tests/test_model_endpoints.py
Add test case for model creation via API calls
> [MRG] Testing model

- .travis.yml
> Cache pip in travis runs

- persephone_api/api_spec.yaml
> [MRG] Fix API schema for corpus creation endpoint

- Pipfile
- persephone_api/api_endpoints/corpus.py
- persephone_api/api_endpoints/label.py
- persephone_api/api_endpoints/model.py
- persephone_api/api_spec.yaml
- persephone_api/db_models.py
- persephone_api/serialization.py
- persephone_api/upload_config.py
- pylintrc
- tests/conftest.py
- tests/test_labels.py
- tests/test_model_endpoints.py
> [WIP] Specify DB tables for phonetic label sets

- persephone_api/api_endpoints/model.py
- persephone_api/api_spec.yaml
- persephone_api/db_models.py
- tests/conftest.py
- tests/test_model_endpoints.py
* Add parameters for specifying error maximums in model training, Closes #85
* implement GET for models by ID, Closes #96
> [MRG] Missing model parameters

- persephone_api/api_endpoints/corpus.py
- persephone_api/api_endpoints/model.py
- tests/test_corpus_endpoint.py
> [WIP] Fix corpus response structure

- Dockerfile
- Pipfile
- Pipfile.lock
- README.rst
- transcription_API_server.py
> [WIP] Run API server from Docker image

- persephone_api/api_endpoints/corpus.py
- persephone_api/api_spec.yaml
> [MRG] Removed the zipfile upload endpoint

- README.rst
- Vagrantfile
- bootstrap.sh
Create a development environment with Vagrant.
Closes #61
> [WIP] Development environment

- examples/curl_example.sh
- persephone_api/api_endpoints/corpus.py
- persephone_api/api_endpoints/model.py
- persephone_api/api_spec.yaml
- persephone_api/db_models.py
- tests/conftest.py
- tests/test_corpus_endpoint.py
- tests/test_model_endpoints.py
- tests/test_train_tiny_yongning_na.py
> [MRG] Change API spec to use camelCase

- persephone_api/api_endpoints/model.py
- tests/test_model_endpoints.py
Make a more informative error response code, closes #123
> [WIP] Added test for invalid corpus when attempting to create model

- Pipfile
- Pipfile.lock
Set minimum version for requests package see: CVE-2018-18074
> [MRG] Pin requests version to avoid security issue

- persephone_api/api_endpoints/backend.py
- persephone_api/api_spec.yaml
- tests/test_API_backend.py
Provide information about what labels the back end can support. Closes #131
> [MRG] Feature backend label types

- persephone_api/api_endpoints/backend.py
- persephone_api/api_spec.yaml
- tests/test_API_backend.py
Provide information about what features the back end can support. Closes #132
> [MRG] backend audio feature type availability

- persephone_api/api_endpoints/audio.py
- persephone_api/api_endpoints/label.py
- persephone_api/api_endpoints/model.py
- persephone_api/api_endpoints/transcription.py
- persephone_api/api_endpoints/utterance.py
- persephone_api/api_spec.yaml
- tests/test_audio_endpoint.py
- tests/test_transcription_endpoint.py
Uniform error response API, closes #64 
Unblocks:
https://github.com/aapeliv/persephone-frontend/issues/19
> [MRG] Specify error response format

- persephone_api/api_endpoints/backend.py
- persephone_api/api_spec.yaml
- tests/test_API_backend.py
Supply information about which file-types are acceptable via API endpoint, closes #6
> [MRG] Feature accepted filetypes

- persephone_api/api_endpoints/label.py
- persephone_api/api_endpoints/model.py
- persephone_api/api_endpoints/transcription.py
- persephone_api/db_models.py
- persephone_api/unicode_handling.py
> [WIP] Create unicode text column

- persephone_api/api_endpoints/audio.py
- persephone_api/api_endpoints/corpus.py
- persephone_api/api_endpoints/label.py
- persephone_api/api_endpoints/model.py
- persephone_api/api_endpoints/transcription.py
- persephone_api/api_endpoints/utterance.py
- persephone_api/api_spec.yaml
- tests/test_audio_endpoint.py
- tests/test_transcription_endpoint.py
Implement pagination for results, closes #114
> [MRG] Create pagination

- persephone_api/api_spec.yaml
Clean up parameter definitions in API spec, closes #154
> [MRG] refactor model ID parameter in API spec

- persephone_api/api_spec.yaml
Specify that 500 error responses are possible in the API specification.
This will go part of the way to fixing issue #142
> [MRG] Specify 500 error respose

- persephone_api/api_endpoints/corpus.py
- persephone_api/db_models.py
- tests/conftest.py
- tests/test_audio_endpoint.py
- tests/test_corpus_endpoint.py
- tests/test_error_format.py
- tests/test_labels.py
- tests/test_model_endpoints.py
- tests/test_train_tiny_yongning_na.py
- tests/test_transcription_endpoint.py
- tests/test_utterance_endpoint.py
> [WIP] Fix issues with corpus creation

- README.rst
- docs/index.rst
- docs/support.rst
Added details about support options in the documentation
> [MRG] Document support options

- CONTRIBUTING.md
Contribution guidelines document, closes #168
> [MRG] contributing guidelines

- Dockerfile
- nginx-app.conf
- supervisor-app.conf
- transcription_API_server.py
- uwsgi.ini
Will be far better for performance and security.
Implementing proper file serving using nginx will close #7
> [WIP] Use nginx to serve the API

- .gitignore
- persephone_api/api_endpoints/audio.py
- persephone_api/api_endpoints/bulk_data.py
- persephone_api/api_endpoints/transcription.py
- persephone_api/api_spec.yaml
- persephone_api/upload_config.py
- tests/test_bulk_uploads.py
Closes #174 
Required for completing the work on the UI for the bulk upload of data: https://github.com/persephone-tools/persephone-frontend/issues/64
> [WIP] Create API endpoint for bulk data upload

- persephone_api/api_endpoints/bulk_data.py
Return results from Zip upload endpoint. Closes #176
> [MRG] Return information about created items in response

- persephone_api/api_endpoints/audio.py
- persephone_api/api_endpoints/bulk_data.py
- persephone_api/api_endpoints/transcription.py
- persephone_api/db_models.py
- persephone_api/unicode_handling.py
- tests/test_unicode_handling.py
Fixes bug with path configuration, closes #180
> [MRG] Fix issue with file paths

- persephone_api/api_endpoints/transcription.py
- persephone_api/api_spec.yaml
- tests/test_transcription_endpoint.py
Feature to create a transcription item from a JSON object (previously you had to upload a file)
Closes #182 
closes #122
> [MRG] Feature transcription from string

- persephone_api/api_endpoints/model.py
> [MRG] Refactor to use transcription creation function

- transcription_API_server.py
> [MRG] Register a 500 error handler
